# Generated by Django 4.2.7 on 2025-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('VISIT_REQUESTED', 'Visit Requested'), ('VISIT_APPROVED', 'Visit Approved'), ('VISIT_REJECTED', 'Visit Rejected'), ('VISIT_RESCHEDULED', 'Visit Rescheduled'), ('VISIT_COMPLETED', 'Visit Completed'), ('VISIT_CANCELLED', 'Visit Cancelled'), ('VISIT_REFUNDED', 'Visit Refunded'), ('BOOKING_REQUESTED', 'Booking Requested'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_REFUNDED', 'Booking Refunded'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('REVIEW_SUBMITTED', 'Review Submitted'), ('REVIEW_RECEIVED', 'Review Received')], max_length=50),
        ),
    ]
