# Generated by Django 4.2.7 on 2025-05-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyamenity',
            options={'verbose_name_plural': 'Property Amenities'},
        ),
    ]
