# Generated by Django 4.2.7 on 2025-05-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='feedback',
        ),
        migrations.AddField(
            model_name='visit',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation or rejection', null=True),
        ),
    ]
